name: Deploy to Hostinger (Yoganesha)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 217.196.57.178
          username: u554097983.yoganesha.cl
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./public_html/
          protocol: ftp
          port: 21
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/versions/**
            README.md
